# --- CONFIGURACIÓN GLOBAL ---
# Nombre de dominio y servidores DNS para los clientes
option domain-name "aula.invertida";
option domain-name-servers 8.8.8.8, 8.8.4.4;

# Tiempos de concesión (Lease Time)
default-lease-time 600;
max-lease-time 7200;

# El servidor es el "jefe" de la red (Autoritativo)
authoritative;

# --- CONFIGURACIÓN DE LA SUBRED ---
# Declaramos la red 192.168.10.0
subnet 192.168.10.0 netmask 255.255.255.0 {

    # RANGO: Repartimos IPs desde la .50 hasta la .100
    range 192.168.10.50 192.168.10.100;

    # PUERTA DE ENLACE: La IP de este servidor (u otro router)
    option routers 192.168.10.1;

    # BROADCAST: Dirección de difusión
    option broadcast-address 192.168.10.255;
}

# --- RESERVA PARA IMPRESORA DEL JEFE ---
group {
    host impresora_jefe {
        hardware ethernet 00:11:22:33:44:55;
        fixed-address 192.168.10.200;
    }
}
